on:
  schedule:
    - cron: '5 15 * * *'
  workflow_dispatch:

jobs:
  single-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up git config
        run: |
          git config --global user.email "cosyq1305@naver.com"
          git config --global user.name "kjh1305"
      - name: Pull latest changes
        run: git pull --rebase
      - name: Make empty commit with KST date
        run: |
          export TZ=Asia/Seoul
          git commit --allow-empty --date="$(date '+%a %b %d %H:%M:%S %Y +0900')" -m "auto commit $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
