# .github/workflows/main.yml

on:
  schedule:
    - cron: '*/5 * * * *' # 매일 정오(UTC)에 실행

jobs:
  single-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: bcanseco/github-contribution-graph-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EMAIL: cosyq1305@naver.com # 본인 이메일로 변경
